import AppKit
import PastefixAppCore

/// Decides whether a pasteboard change may enter history. Filters run in order; any `false` wins.
protocol CaptureFilter: Sendable {
    func shouldCapture(_ candidate: CaptureCandidate, types: [NSPasteboard.PasteboardType]) -> Bool
}

/// Password managers and autofill mark their writes; those never enter history (Critical Invariant 12).
struct ConcealedTypeFilter: CaptureFilter {
    static let markers: [NSPasteboard.PasteboardType] = [
        .init("org.nspasteboard.ConcealedType"), .init("org.nspasteboard.TransientType"), .init("org.nspasteboard.AutoGeneratedType"),
    ]
    func shouldCapture(_ candidate: CaptureCandidate, types: [NSPasteboard.PasteboardType]) -> Bool {
        !types.contains { Self.markers.contains($0) }
    }
}

/// Polls the general pasteboard's change count (macOS offers no notification) and hands
/// each new item, once, to `onCapture` after the filter chain approves it.
@MainActor
final class PasteboardMonitor {
    private let pasteboard: NSPasteboard
    private let filters: [any CaptureFilter]
    private let onCapture: (CaptureCandidate) -> Void
    private var timer: Timer?
    private var lastChangeCount: Int

    init(pasteboard: NSPasteboard = .general, filters: [any CaptureFilter], onCapture: @escaping (CaptureCandidate) -> Void) {
        self.pasteboard = pasteboard; self.filters = filters; self.onCapture = onCapture
        self.lastChangeCount = pasteboard.changeCount
    }

    var isRunning: Bool { timer != nil }

    func start() {
        guard timer == nil else { return }
        lastChangeCount = pasteboard.changeCount   // never back-fill what was already there
        let t = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.tick() }
        }
        RunLoop.main.add(t, forMode: .common)      // keeps firing while menus are open
        timer = t
    }

    func stop() { timer?.invalidate(); timer = nil }

    private func tick() {
        let count = pasteboard.changeCount
        guard count != lastChangeCount else { return }
        lastChangeCount = count
        guard let candidate = Self.read(pasteboard) else { return }
        let types = pasteboard.types ?? []
        for filter in filters where !filter.shouldCapture(candidate, types: types) { return }
        onCapture(candidate)
    }

    /// One read per change. Rich content only when a rich type is actually declared (Plan 2a lesson).
    static func read(_ pb: NSPasteboard) -> CaptureCandidate? {
        var c = CaptureCandidate()
        c.plainText = pb.string(forType: .string)
        if pb.availableType(from: [.rtf, .rtfd, .html]) != nil,
           let attributed = pb.readObjects(forClasses: [NSAttributedString.self], options: nil)?.first as? NSAttributedString {
            c.richRTFD = try? attributed.data(from: NSRange(location: 0, length: attributed.length),
                                              documentAttributes: [.documentType: NSAttributedString.DocumentType.rtfd])
        }
        if let png = pb.data(forType: .png), let rep = NSBitmapImageRep(data: png) {
            c.imagePNG = png; c.imagePixelWidth = rep.pixelsWide; c.imagePixelHeight = rep.pixelsHigh
        } else if let tiff = pb.data(forType: .tiff), let rep = NSBitmapImageRep(data: tiff),
                  let png = rep.representation(using: .png, properties: [:]) {
            c.imagePNG = png; c.imagePixelWidth = rep.pixelsWide; c.imagePixelHeight = rep.pixelsHigh
        }
        if let app = NSWorkspace.shared.frontmostApplication {
            c.sourceBundleID = app.bundleIdentifier; c.sourceAppName = app.localizedName
        }
        guard c.plainText != nil || c.imagePNG != nil else { return nil }
        return c
    }
}
