import AppKit
import PastefixAppCore

/// Decides whether a pasteboard change may enter history. Filters run in order; any `false` wins.
protocol CaptureFilter: Sendable {
    func shouldCapture(_ candidate: CaptureCandidate, types: [NSPasteboard.PasteboardType]) -> Bool
}

/// Password managers and autofill mark their writes; those never enter history (Critical Invariant 12).
/// Covers both the current nspasteboard.org marker spellings and the legacy ones still emitted by
/// older (and some still-shipping) apps. Note: `NSPasteboard.types` reports only the first
/// pasteboard item's types, so a marker on a second item is invisible here — consistent with
/// `PasteboardMonitor.read`, which is also first-item-only; don't "fix" just one half.
struct ConcealedTypeFilter: CaptureFilter {
    static let markers: [NSPasteboard.PasteboardType] = [
        .init("org.nspasteboard.ConcealedType"), .init("org.nspasteboard.TransientType"), .init("org.nspasteboard.AutoGeneratedType"),
        .init("de.petermaurer.TransientPasteboardType"), .init("com.typeit4me.clipping"), .init("Pasteboard generator type"),
    ]
    func shouldCapture(_ candidate: CaptureCandidate, types: [NSPasteboard.PasteboardType]) -> Bool {
        !types.contains { Self.markers.contains($0) }
    }
}

/// Polls the general pasteboard's change count (macOS offers no notification) and hands
/// each new item, once, to `onCapture` after the filter chain approves it.
@MainActor
final class PasteboardMonitor {
    private let pasteboard: NSPasteboard
    private let filters: [any CaptureFilter]
    private let maxImageBytes: Int
    private let onCapture: (CaptureCandidate) -> Void
    private var timer: Timer?
    private var lastChangeCount: Int

    init(pasteboard: NSPasteboard = .general, filters: [any CaptureFilter], maxImageBytes: Int,
         onCapture: @escaping (CaptureCandidate) -> Void) {
        self.pasteboard = pasteboard; self.filters = filters; self.maxImageBytes = maxImageBytes; self.onCapture = onCapture
        self.lastChangeCount = pasteboard.changeCount
    }

    var isRunning: Bool { timer != nil }

    func start() {
        guard timer == nil else { return }
        lastChangeCount = pasteboard.changeCount   // never back-fill what was already there
        let t = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.tick() }
        }
        RunLoop.main.add(t, forMode: .common)      // keeps firing while menus are open
        timer = t
    }

    func stop() { timer?.invalidate(); timer = nil }

    private func tick() {
        let count = pasteboard.changeCount
        guard count != lastChangeCount else { return }
        let types = pasteboard.types ?? []
        // `clearContents()` bumps changeCount immediately but the writer's subsequent
        // `setData`/`setString` calls do not; landing here mid-write would otherwise see an
        // empty pasteboard and permanently skip the item once `lastChangeCount` advances past
        // it. Leave `lastChangeCount` alone so the next tick retries the same change.
        guard !types.isEmpty else { return }
        lastChangeCount = count
        // Marker check first, against types sampled before any content is touched, so a
        // concealed item's bytes are never even read under the guise of deciding whether they
        // may be captured. The candidate here is a placeholder: today's only filter
        // (`ConcealedTypeFilter`) is types-only; a future content-aware filter would need to
        // run after `read` below and re-verify `changeCount` itself before trusting `candidate`.
        guard filters.allSatisfy({ $0.shouldCapture(CaptureCandidate(), types: types) }) else { return }
        guard let candidate = Self.read(pasteboard, maxImageBytes: maxImageBytes) else { return }
        // The pasteboard can change again while `read` was busy (RTFD conversion, image
        // decode/re-encode can take real time) — if it did, `candidate` may be a mix of this
        // change's marker types and a later change's content, which must never be recorded.
        // Roll back one so the next tick sees the newer count as unseen and reprocesses it
        // cleanly, rather than treating today's mixed read as final.
        guard pasteboard.changeCount == count else {
            lastChangeCount = count - 1
            return
        }
        onCapture(candidate)
    }

    /// One read per change. Rich content only when a rich type is actually declared (Plan 2a lesson).
    /// `maxImageBytes` lets an over-budget image skip decoding/re-encoding entirely instead of
    /// paying that cost on the main actor only for `HistoryStore.record` to reject it.
    static func read(_ pb: NSPasteboard, maxImageBytes: Int) -> CaptureCandidate? {
        var c = CaptureCandidate()
        c.plainText = pb.string(forType: .string)
        if pb.availableType(from: [.rtf, .rtfd, .html]) != nil,
           let attributed = pb.readObjects(forClasses: [NSAttributedString.self], options: nil)?.first as? NSAttributedString {
            c.richRTFD = try? attributed.data(from: NSRange(location: 0, length: attributed.length),
                                              documentAttributes: [.documentType: NSAttributedString.DocumentType.rtfd])
        }
        if let png = pb.data(forType: .png) {
            // Size before decode: constructing the rep just to read pixel dimensions would
            // otherwise decode an image the store is about to reject anyway.
            if png.count <= maxImageBytes, let rep = NSBitmapImageRep(data: png) {
                c.imagePNG = png; c.imagePixelWidth = rep.pixelsWide; c.imagePixelHeight = rep.pixelsHigh
            }
        } else if let tiff = pb.data(forType: .tiff),
                  // Heuristic gate: a PNG re-encode of an already-oversized TIFF is essentially
                  // certain to still be over `maxImageBytes` (PNG rarely beats raw TIFF by more
                  // than ~4x), so skip the decode + re-encode outright rather than burning
                  // main-actor time on a conversion whose result will be thrown away. The store
                  // still enforces the real cap on whatever PNG bytes do come out below.
                  tiff.count <= 4 * maxImageBytes,
                  let rep = NSBitmapImageRep(data: tiff),
                  let png = rep.representation(using: .png, properties: [:]),
                  png.count <= maxImageBytes {
            c.imagePNG = png; c.imagePixelWidth = rep.pixelsWide; c.imagePixelHeight = rep.pixelsHigh
        }
        if let app = NSWorkspace.shared.frontmostApplication {
            c.sourceBundleID = app.bundleIdentifier; c.sourceAppName = app.localizedName
        }
        guard c.plainText != nil || c.imagePNG != nil else { return nil }
        return c
    }
}
