import AppKit

/// Password managers and autofill mark their writes; those never enter history (Critical Invariant 12).
/// Covers both the current nspasteboard.org marker spellings and the legacy ones still emitted by
/// older (and some still-shipping) apps. Note: `NSPasteboard.types` reports only the first
/// pasteboard item's types, so a marker on a second item is invisible here — consistent with
/// `PasteboardMonitor.read`, which is also first-item-only; don't "fix" just one half.
public struct ConcealedTypeFilter: CaptureFilter {
    public static let markers: [NSPasteboard.PasteboardType] = [
        .init("org.nspasteboard.ConcealedType"), .init("org.nspasteboard.TransientType"), .init("org.nspasteboard.AutoGeneratedType"),
        .init("de.petermaurer.TransientPasteboardType"), .init("com.typeit4me.clipping"), .init("Pasteboard generator type"),
    ]
    public init() {}
    private static func isConcealed(_ types: [NSPasteboard.PasteboardType]) -> Bool {
        types.contains { markers.contains($0) }
    }
    public func shouldRead(types: [NSPasteboard.PasteboardType], context: CaptureContext) -> Bool { !Self.isConcealed(types) }
    public func shouldCapture(_ candidate: CaptureCandidate, types: [NSPasteboard.PasteboardType], context: CaptureContext) -> Bool { !Self.isConcealed(types) }
}
